[tool.poetry]
name = "pydevto"
version = "0.1.0"
description = "Unofficial dev.to api for python"
readme = "README.md"
repository = "https://github.com/lpellis/pydevto"
license = "MIT"
authors = ["'Loftie <lpellis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
beautifulsoup4 = "^4.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
